version: "3"

services:
  backend:
    platform: linux/amd64
    build: ./back
    ports:
      - "3000:3000"
    volumes:
      - /backend/node_modules

  frontend:
    platform: linux/amd64
    build: ./front
    ports:
      - "8000:8000"
    volumes:
      - /frontend/node_modules
